#ifndef APPCONFIG_H
#define APPCONFIG_H

#define CLIENT_BUILD_KEY "drHSV2XQ"
#define ENCRYPT_USER_DATA true
#define CACHE_RAMOBJECT_DATA true
#define CACHE_LOCAL_DATA true

//#define FORCE_WELCOME_SCREEN

#endif // APPCONFIG_H
