site_name: Ramses
site_url: https://ramses.rxlab.guide
repo_url: https://github.com/RxLaboratory/Ramses/
edit_uri: edit/master/src-docs/docs/
site_description: The Ramses comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2022 <a href="https://rxlaboratory.org">Rainbox Laboratory</a> and <a href="https://duduf.com">Nicolas Dufresne</a>'
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
extra:
    collapse_toc: true
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - toc
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - v0.6 (Beta): index.md
    - Quick start: quickstart/index.md
    - Principles:
        - Introduction: pipeline/index.md
        - Administration: pipeline/administration.md
        - Pipeline: pipeline/pipeline.md
        - Production tracking: pipeline/production.md
        - Planning: pipeline/planning.md
    - Documentation:
        - Introduction: components/index.md
        - Ramses Application:
            - Introduction: components/client/index.md
            - Installation: components/client/install.md
            - Overview and settings: components/client/settings.md
            - Administration:
                - Introduction: components/client/admin.md
                - Users: components/client/users.md
                - Projects: components/client/projects.md
                - Template Steps: components/client/templatesteps.md
                - Template Asset Groups: components/client/templateassetgroups.md
                - States: components/client/states.md
                - File Types: components/client/filetypes.md
                - Applications: components/client/applications.md
            - Project settings:
                - Introduction: components/client/project.md
                - Steps: components/client/steps.md
                - Pipe Types: components/client/pipetypes.md
                - Asset Groups: components/client/assetgroups.md
                - Assets: components/client/assets.md
                - Sequences: components/client/sequences.md
                - Shots: components/client/shots.md
            - Pipeline editor: components/client/pipeline.md
            - Asset and shot production tracking: components/client/production.md
            - Schedule and planning: components/client/schedule.md
        - Ramses Add-ons:
            - General Information: components/addons/index.md
            - Autodesk Maya:
                - Maya Add-on: components/addons/maya.md
                - Maya pipeline: components/addons/maya-pipeline.md
                - Scene setup: components/addons/maya-scenesetup.md
                - Publish settings: components/addons/maya-publish.md
                - Import settings: components/addons/maya-import.md
                - Extensibility: components/addons/maya-extend.md
        - Ramses Tree:
            - Introduction: components/files/index.md
            - Naming scheme: components/files/naming.md
            - Folder structure: components/files/tree.md
        - Ramses Server:
            - Introduction: components/server/index.md
            - Installation: components/server/install.md
            - Install from source: components/server/install-src.md
            - Docker (MySQL): components/server/install-docker-mysql.md
            - Docker (SQLite): components/server/install-docker-sqlite.md
            - Configuration: components/server/config.md
            - Update: components/server/update.md
            - Administration: components/server/admin.md
    - Extensibility:
        - Introduction: dev/index.md
        - Objects: dev/objects.md
        - Files and Folders:
            - Naming: dev/files/naming.md
        - Scripting API (Add-ons):
            - Reference: dev/add-ons-reference/index.md
            - Constants: dev/add-ons-reference/enum.md
            - Ramses: dev/add-ons-reference/ramses.md
            - RamAsset: dev/add-ons-reference/ram_asset.md
            - RamAssetGroup: dev/add-ons-reference/ram_assetgroup.md
            - RamDaemonInterface: dev/add-ons-reference/ram_daemon_interface.md
            - RamFileInfo: dev/add-ons-reference/ram_file_info.md
            - RamFileManager: dev/add-ons-reference/ram_file_manager.md
            - RamFileType: dev/add-ons-reference/ram_filetype.md
            - RamItem: dev/add-ons-reference/ram_item.md
            - RamMetaDataManager: dev/add-ons-reference/ram_metadata_manager.md
            - RamObject: dev/add-ons-reference/ram_object.md
            - RamPipe: dev/add-ons-reference/ram_pipe.md
            - RamPipeFile: dev/add-ons-reference/ram_pipefile.md
            - RamProject: dev/add-ons-reference/ram_project.md
            - RamSequence: dev/add-ons-reference/ram_sequence.md
            - RamSettings: dev/add-ons-reference/ram_settings.md
            - RamShot: dev/add-ons-reference/ram_shot.md
            - RamState: dev/add-ons-reference/ram_state.md
            - RamStatus: dev/add-ons-reference/ram_status.md
            - RamStep: dev/add-ons-reference/ram_step.md
            - RamUser: dev/add-ons-reference/ram_user.md
            - Dev Notes: dev/add-ons-reference/implementation.md
        - Daemon API:
            - Reference: dev/daemon-reference/index.md
            - ping: dev/daemon-reference/ping.md
            - raise: dev/daemon-reference/raise.md
            - create: dev/daemon-reference/create.md
            - getRamsesFolder: dev/daemon-reference/getRamsesFolder.md
            - getObjets: dev/daemon-reference/getObjects.md
            - getPath: dev/daemon-reference/getPath.md
            - getProjects: dev/daemon-reference/getProjects.md
            - getCurrentProject: dev/daemon-reference/getCurrentProject.md
            - setCurrentProject: dev/daemon-reference/setCurrentProject.md
            - getData: dev/daemon-reference/getData.md
            - setData: dev/daemon-reference/setData.md
            - uuidFromPath: dev/daemon-reference/uuidFromPath.md
        - Server API: dev/server-reference/index.md
    - ...:
        - Credits: credits.md
        - Changelog:
            - General: changelog.md
            - Application: changelog-app.md
            - Maya: changelog-maya.md
            - Server: changelog-server.md
            - API: changelog-api.md
        - Licenses:
            - GNU GPLv3: licenses/gnu-gpl.md
            - Documentation license: licenses/gfdl.md
